- hosts: web
  tasks:
  - - apt:
        pkg: python3
        stat: present
      name: Install python3
    - apt:
        pkg: nginx
        stat: present
      name: Install nginx
  - - copy:
        dest: scripts/
        src: src/exploit.py
      name: Copy exploit.py
    - copy:
        dest: scripts/
        src: src/consumer.py
      name: Copy consumer.py
  - vars:
    - bad_guys:
      - '4815162342'
      - '3133780085'
